<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="workflow"
    nsURI="http://workflow/1.0" nsPrefix="workflow">
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//ComponentInstanceInput" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//ComponentInstanceOutput" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="family" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activityType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentDefinition" eType="#//IComponentDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Receiver" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="senders" eType="#//Sender"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sender" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivers" eType="#//Receiver"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowInput" eSuperTypes="#//Sender #//Receiver #//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="Workflow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//ComponentInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//WorkflowInput" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//WorkflowOutput" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentDefinition" eType="#//IComponentDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowOutput" eSuperTypes="#//Receiver #//Sender #//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstanceInput" eSuperTypes="#//Port #//Receiver"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstanceOutput" eSuperTypes="#//Port #//Sender #//Receiver"/>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IComponentDefinition" interface="true"/>
</ecore:EPackage>
